name: 'expo-eas-build-submit'
description: 'Build and submit Expo app using EAS with CI-managed secrets'
inputs:
  platform:
    required: false
    default: 'ios'
  profile:
    required: false
    default: 'production'
  expo_token:
    required: true
  cert_password:
    required: true
  asc_api_key_id:
    required: true
  asc_api_key_issuer_id:
    required: true
  ios_cert_decrypt_key:
    required: false
  ios_cert_decrypt_key_2:
    required: false
  commit_message:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Xcode
      if: ${{ inputs.platform == 'ios' }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Import GPG private key
      shell: bash
      run: echo "${{ inputs.ios_gpg_private_key }}" | gpg --batch --yes --import --quiet
    - name: Decrypt iOS build credentials
      working-directory: ios/certs
      shell: bash
      run: |
        echo "${{ inputs.ios_gpg_passphrase }}" | \
        gpg --quiet --batch --yes --trust-model always --passphrase-fd 0 --output dist.p12 dist.p12.gpg 2>/dev/null

        echo "${{ inputs.ios_gpg_passphrase }}" | \
        gpg --quiet --batch --yes --trust-model always --passphrase-fd 0 --output profile.mobileprovision profile.mobileprovision.gpg 2>/dev/null

        echo "${{ inputs.ios_gpg_passphraseE }}" | \
        gpg --quiet --batch --yes --trust-model always --passphrase-fd 0 --output AuthKey.p8 AuthKey.p8.gpg 2>/dev/null

        echo "${{ inputs.ios_gpg_passphrase }}" | \
        gpg --quiet --batch --yes --trust-model always --passphrase-fd 0 --output ../../credentials.json credentials.json.gpg 2>/dev/null
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
    - name: Setup Expo & EAS
      uses: expo/expo-github-action@8.2.1
      with:
        token: ${{ inputs.expo_token }}
        expo-version: latest
        eas-version: latest
    - name: 🚀 Move the fastline file
      if: ${{ inputs.platform == 'ios' }}
      shell: bash
      run: |
        mkdir -p fastlane
        mv ios/certs/Fastfile fastlane/Fastfile
    - name: 🔢 Calculate NEXT build number
      if: ${{ inputs.platform == 'ios' }}
      id: buildnum
      shell: bash
      run: fastlane ios calculate_build
      env:
        ASC_API_KEY_ID: ${{ inputs.asc_api_key_id }}
        ASC_API_KEY_ISSUER_ID: ${{ inputs.asc_api_key_issuer_id }}
        NEW_BUILD_NUMBER: ${{ env.NEW_BUILD_NUMBER }}
    - name: 🏗 Install EAS local builds
      shell: bash
      run: npm i eas-cli-local-build-plugin
    - name: 🛠 Build app
      shell: bash
      env:
        GIT_COMMIT_HASH: ${{ github.sha }}
        NEW_BUILD_NUMBER: ${{ steps.buildnum.outputs.new_build_number }}
      run: |
        echo "Using NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER"
        npx expo install expo-dev-client
        eas build --local --non-interactive \
          --platform=${{ inputs.platform }} \
          --profile=${{ inputs.profile }} \
          --output="app.${{ inputs.platform == 'ios' && 'ipa' || 'apk' }}"
    - name: 🚀 Upload to TestFlight
      if: ${{ inputs.platform == 'ios' }}
      shell: bash
      run: fastlane ios upload_testflight
      env:
        ASC_API_KEY_ID: ${{ inputs.asc_api_key_id }}
        ASC_API_KEY_ISSUER_ID: ${{ inputs.asc_api_key_issuer_id }}
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
    - name: 📦 Submit app (Android only)
      if: ${{ inputs.platform != 'ios' }}
      shell: bash
      env:
        ASC_API_KEY_ID: ${{ inputs.asc_api_key_id }}
        ASC_API_KEY_ISSUER_ID: ${{ inputs.asc_api_key_issuer_id }}
      run: |
        eas submit \
          --platform=${{ inputs.platform }} \
          --non-interactive \
          --path="app.${{ inputs.platform == 'ios' && 'ipa' || 'apk' }}" \
          --profile=${{ inputs.profile }}